default:
  token: 'put your token here'
  interval: '60' # How much minutes to wait before sending another batch of messages (Default: 60)
  debug_mode: 'false' # If set to true, you will get a log in the console every time a message is sent (Default: false)
  channels: # Channels where to send the message
    - 'xxxxxxxxxxxxxxxxxxx'
    - 'xxxxxxxxxxxxxxxxxxx' # etc