default:
  token: 'put your token here'
  interval: 60 # How many minutes to wait before sending another batch of messages (Default: 60)

  # This setting overrides the 'interval' value set above
  randomize_interval:
    enabled: false  # If set to true, your interval is randomized based on the values below (Default: false)
    minimum_interval: 60 # Minimum interval in minutes (Default: 60)
    maximum_interval: 70 # Maximum interval in minutes (Default: 70)

  avoid_spam:
    enabled: false # If set to true, the script prevents double-posting (Default: false)
    # Set both minimum and maximum to the same number if you want to only post when that number is reached, and not randomize
    minimum_messages: 2 # Minimum amount of messages other people post before you repost yours. (Default: 2)
    maximum_messages: 2 # Maximum amount of messages other people post before you repost yours. (Default: 2)

  wait_before_start: 0 # How many minutes to wait before starting the script (Default: 0)
  debug_mode: false # If set to true, you will get a log in the console every time a message is sent (Default: false)
  channels: # Channels where to send the message
    - 'xxxxxxxxxxxxxxxxxxx'
    - 'xxxxxxxxxxxxxxxxxxx' # etc
